# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u4ef7\u683c')),
                ('isDelete', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
            ],
            options={
                'db_table': 'orderDetailInfo',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('ototal', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='\u603b\u4ef7')),
                ('state', models.CharField(default='0', max_length=1, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('address', models.CharField(max_length=127)),
                ('payTime', models.DateTimeField(default=None, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('payMethod', models.IntegerField(default=0, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo')),
            ],
            options={
                'db_table': 'orderInfo',
            },
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo'),
        ),
    ]
