# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u4ef7\u683c'),
        ),
    ]
