# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('gdesc', models.TextField(verbose_name='\u5546\u54c1\u63cf\u8ff0')),
                ('ginfo', models.CharField(default=' ', max_length=100, verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('gpath', models.CharField(max_length=1000, verbose_name='list\u8def\u5f84')),
                ('gdetail', models.CharField(default=' ', max_length=1000, verbose_name='detail\u8def\u5f84')),
                ('gunit', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u5355\u4f4d')),
                ('gcount', models.IntegerField(default=1000, verbose_name='\u5546\u54c1\u5e93\u5b58')),
                ('gclick', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u70b9\u51fb\u91cf')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u5206\u7c7b')),
                ('isDelete', models.BooleanField(default=False)),
                ('cssClass', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('img_path', models.CharField(max_length=127, verbose_name='\u5546\u54c1\u5206\u7c7b\u56fe\u7247')),
            ],
            options={
                'db_table': 'typeinfo',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeInfo'),
        ),
    ]
