# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('pwd', models.CharField(max_length=40, verbose_name='\u5bc6\u7801')),
                ('isdelete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('code', models.CharField(max_length=6, verbose_name='\u90ae\u7f16')),
                ('email', models.CharField(max_length=30, verbose_name='\u90ae\u7bb1')),
                ('sendee', models.CharField(max_length=20, verbose_name='\u6536\u4ef6\u4eba')),
                ('addrs', models.TextField(blank=True, null=True)),
                ('defaultAddr', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
